name: Feature Request
description: Suggest an improvement for VoltYTM
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      options:
        - label: I searched existing issues for a similar request.
          required: true
  - type: textarea
    attributes:
      label: Problem
      description: What user problem should this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
  - type: textarea
    attributes:
      label: Additional Context
