// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockReason } from "./BlockReason";

export type NetworkDecision = { "action": "allow" } | { "action": "block", "reason": BlockReason };
