// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SerializedCookie = { name: string, value: string, domain: string | null, path: string | null, expires: bigint | null, httpOnly: boolean | null, secure: boolean | null, };
